### ISSUE TITLE
[BUG] Repairing all packages doesn't seem to be the same as repairing packages individually

### ISSUE THREAD

**Issue by NoTuxNoBux** [kumaS-nu/NuGet-importer-for-Unity#24] opened 2022-03-14 15:37 UTC
**Describe the bug**
If I have a NuGet setup where a couple of packages are installed in my `rootPackages.xml`, and I remove the `NuGet` root folder and `Packages/FooDependency` folders, doing `Repair Packages` through Unity does not restore these folders.

**To Reproduce**
1. Install some packages.
2. Remove the `NuGet` folder.
3. Remove the installed package folders in `Packages` (e.g. `Packages/Foo`).
4. Restart Unity.
5. Errors occur because the packages are missing their files (expected). Click `Repair packages`.
6. The repair finishes, but the files are not restored.

**Expected behavior**
The files are restored.

**Desktop (please complete the following information):**
 - OS: Linux x86-64
 - Unity Version: 2020.3.26f1
 - Package Version 2.1.2

**Additional context**
Clicking `Repair` on each package in the list `Installed packages` _does_ properly restore the folders, but it's a bit cumbersome as you need to click them one by one.

The reason I was testing this is because when you share a project with colleagues and use Git, you are only going to be sharing the package configuration (`rootPackages.xml` as general package configuration, and perhaps `packages.config` as lock file), but not the actual contents of the packages. It'd be ideal if the package could assess that some packages are missing on Unity startup (project load) and install the missing ones if necessary. This is what NuGetForUnity does as well. Barring that, reparing them all manually through the button could also work.

**Comment by kumaS-nu** [comment] 2022-03-19 15:02
The cause has not been determined, but it will be fixed soon.
In addition, package auto-repair should be enabled as an option.

**Closed** 2022-03-29 16:56 UTC
Labels: bug, enhancement
